import { NextStepProps } from 'nextstepjs';

export const tourSteps: NextStepProps['steps'] = [
  {
    tour: 'onboardingTour',
    steps: [
      {
        icon: '👋',
        title: 'Welcome',
        content: "Let's get you started with Bridge!",
        side: 'right',
        showControls: true,
        showSkip: true,
      },
      {
        icon: '🏫',
        title: 'Branch Selector',
        content: 'Click here to manage your branches and send new invites',
        side: 'bottom',
        selector: '#org-selector',
        showControls: true,
      },
      {
        icon: '🚗',
        title: 'Vehicle',
        content: 'Click here to manage your vehicles',
        side: 'right',
        selector: '#Vehicles',
        nextRoute: '/vehicles',
        showControls: true,
      },
      {
        icon: '🚗',
        title: 'Add Vehicle',
        content: 'Click on the add vehicle button to add a new vehicle',
        side: 'left',
        selector: '#add-vehicle',
        nextRoute: '/vehicles/add',
        prevRoute: '/dashboard',
        showControls: true,
      },
      {
        icon: '🚗',
        title: 'Add Vehicle Information',
        content: 'Fill in the vehicle information',
        side: 'left',
        selector: '#vehicle-form',
        nextRoute: '/vehicles',
        prevRoute: '/vehicles',
        showControls: true,
      },
      {
        icon: '⚙️',
        title: 'Settings',
        content: 'Click on the settings page',
        side: 'top',
        selector: '#Settings',
        nextRoute: '/settings',
        showControls: true,
        prevRoute: '/vehicles/add',
      },
      {
        icon: '⚙️',
        title: 'Settings Page',
        content: 'Configure your settings as per your need',
        side: 'left',
        selector: '#settings-page',
        showControls: true,
        nextRoute: '/admission',
      },
      {
        icon: '🎉',
        title: 'You are Ready!',
        content: 'You can start adding students to your school',
        side: 'top',
        showControls: true,
        prevRoute: '/settings',
      },
    ],
  },
];
