export const form4AFieldNames = {
  licence_authority_1: 'licence_authority_1',
  licence_authority_2: 'licence_authority_2',
  surname_middlename_firstname: 'surname_middlename_firstname',
  guardian_name: 'guardian_name',
  ever_disqualified: 'ever_disqualified',
  ever_barred_from_requesting_country: 'ever_barred_from_requesting_country',
  fitness_subjected: 'fitness_subjected',
  blood_group: 'blood_group',
  previously_held_idp: 'previously_held_idp',
  conviction: 'conviction',
  place_of_birth_and_country: 'place_of_birth_and_country',
  educational_qualification: 'educational_qualification',
  birth_date: 'birth_date',
  present_address: 'present_address',
  permanent_address: 'permanent_address',
  mobile_number: 'mobile_number',
  email_id: 'email_id',
  identification_mark_1: 'identification_mark_1',
  identification_mark_2: 'identification_mark_2',
};
