// Re-export enum values as constants for easier usage
export const NOTIFICATION_TYPES = {
  // Payment & Financial
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  INSTALLMENT_DUE: 'INSTALLMENT_DUE',
  INSTALLMENT_OVERDUE: 'INSTALLMENT_OVERDUE',
  PAY_LATER_REMINDER: 'PAY_LATER_REMINDER',
  REFUND_PROCESSED: 'REFUND_PROCESSED',

  // License & Testing
  LEARNING_TEST_TODAY: 'LEARNING_TEST_TODAY',
  ELIGIBLE_FOR_DRIVING_TEST: 'ELIGIBLE_FOR_DRIVING_TEST',
  LICENSE_ISSUED: 'LICENSE_ISSUED',
  LICENSE_RENEWAL_DUE: 'LICENSE_RENEWAL_DUE',

  // Vehicle Management
  VEHICLE_DOCUMENT_EXPIRING: 'VEHICLE_DOCUMENT_EXPIRING',
  VEHICLE_DOCUMENT_EXPIRED: 'VEHICLE_DOCUMENT_EXPIRED',
  VEHICLE_MAINTENANCE_DUE: 'VEHICLE_MAINTENANCE_DUE',

  // Training & Sessions
  SESSION_TODAY: 'SESSION_TODAY',
  SESSION_CANCELLED: 'SESSION_CANCELLED',
  SESSION_RESCHEDULED: 'SESSION_RESCHEDULED',

  // RTO Services
  RTO_STATUS_UPDATED: 'RTO_STATUS_UPDATED',
  RTO_SERVICE_COMPLETED: 'RTO_SERVICE_COMPLETED',
  RTO_TATKAL_DEADLINE: 'RTO_TATKAL_DEADLINE',

  // Administrative
  NEW_CLIENT_ADMISSION: 'NEW_CLIENT_ADMISSION',
  REPORT_READY: 'REPORT_READY',
  LOW_CAPACITY_WARNING: 'LOW_CAPACITY_WARNING',
} as const;

export const ENTITY_TYPES = {
  CLIENT: 'CLIENT',
  PAYMENT: 'PAYMENT',
  VEHICLE: 'VEHICLE',
  SESSION: 'SESSION',
  RTO_SERVICE: 'RTO_SERVICE',
  LICENSE: 'LICENSE',
} as const;

// These types will be inferred from the database schema
export type NotificationType = keyof typeof NOTIFICATION_TYPES;
export type EntityType = keyof typeof ENTITY_TYPES;
