import type { Metadata } from 'next';
import { Manrope, Space_Grotesk } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import './globals.css';
import { Toaster } from 'sonner';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { NextStepProvider } from 'nextstepjs';
import { OnboardingWrapper } from '@/providers/onboarding-wrapper';
import { markOnboardingComplete } from '@/server/actions/user';
import { TourWrapper } from '@/components/tour-wrapper';

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
});

const spaceGrotesk = Space_Grotesk({
  variable: '--font-space-grotesk',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Bridge',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${manrope.variable} ${spaceGrotesk.variable} antialiased`}>
          <Toaster closeButton duration={3000} />
          <NuqsAdapter>
            <NextStepProvider>
              <TourWrapper>
                <OnboardingWrapper>{children}</OnboardingWrapper>
              </TourWrapper>
            </NextStepProvider>
          </NuqsAdapter>
        </body>
      </html>
    </ClerkProvider>
  );
}
